name: inputyml

on:
 workflow_dispatch:
  inputs:
     name: 
       description: 'Name'
       type: string
       default: novak
       required: true
     team:
       description: 'team name'
       type: string
       default: india
       required: true
     toss:
       description: 'who won the toss?'
       type: boolean
       required: false
     ground:
       description: 'ground name'
       type: choice
       options:
        - perth
        - sydney
       

jobs:
 inputtest:
   runs-on: ubuntu-latest

   steps:
    - name: inputstep
      run: echo "${{ inputs.name}}", "${{ inputs.team}}", "${{ inputs.ground}}"
    
