name: inputyml

on:
 workflow_dispatch:
  inputs:
     name: 
       description: 'Name'
       type: string
       default: novak

jobs:
 inputtest:
   runs-on: ubuntu-latest

   steps:
    - name: inputstep
      run: echo "iput test"
