name: Build and deploy ASP.Net Core app 

on:
 push:
  branches: [ feature/test]

jobs:
 Build:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v6.0.1
   - name: Setup .NET Core SDK
     uses: actions/setup-dotnet@v5.0.1
   - name: Build
     run: |
       dotnet build 
   
   
 
